name: Build & Test

on: 
  workflow_dispatch:
    inputs:
      TEST_PLAN:
        description: "Which Test Plan should use"
        required: false
        default: "UnitTests"
        type: string

  workflow_call:
    inputs:
      TEST_PLAN: 
        description: "Which Test Plan should use"
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }} 
  cancel-in-progress: true

jobs:
  build:
    name: "Build and test"
    runs-on: macos-13
    timeout-minutes: 30
    env:
      PROJECT_NAME: "Marvel.xcodeproj"
      SCHEME: "Marvel"
      DESTINATION: "platform=iOS Simulator,name=iPhone 15 Pro"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Checking and saving cache
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData/Marvel-*/SourcePackages
            ~/Library/Developer/Xcode/DerivedData/Marvel-*/Build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}

      - name: Setup Xcode latest version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build & Test 
        run: |
          /usr/bin/xcodebuild test \
            -project "$PROJECT_NAME" \
            -scheme "$SCHEME" \
            -testPlan ${{ inputs.TEST_PLAN }} \
            -destination "$DESTINATION" \
            -resultBundlePath testResults

      - name: Upload test results 
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: testResults.xcresult
          path: testResults.xcresult