name: Pull Request Run Unit Tests

on: 
    pull_request: 
      branches:
        - 'develop'

jobs:
    build: 
        uses: ./.github/workflows/build-and-test.yml
        with: 
            TEST_PLAN: "UnitTests"