name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.3.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build and Test MacOS
      run: xcodebuild clean build test -project marvel-project-main/Marvel.xcodeproj -scheme "Marvel" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
